language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
os: linux
install:
  - pip install tox-travis
  - gem install fpm
script:
  - tox
  - make deb
deploy:
  provider: releases
  api_key: '$GITHUB_API_KEY'
  file:
    - '*.deb'
    - '*.rpm'
  skip_cleanup: true
  on:
    tags: true
